FROM node:20-alpine

RUN npm install -g npm@latest

WORKDIR /app

# Copy file cấu hình thư viện vào
COPY package*.json ./

# Cài đặt thư viện 
RUN npm install
RUN npm install -g nodemon

CMD ["npm", "run", "dev"]