apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-backend-deployment
spec:
  replicas: 1 # Số lượng container
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          # image: khiemdg/devsecops-backend:latest # Image trên Docker Hub
          # image: 20.78.47.90:80/devsecops-app/devsecops-backend:latest # Image trên Harbor
          # image: acrdevsecopsnt114.azurecr.io/devsecops-backend:latest # Image trên Azure Container Registry
          image: acrdevsecopsnt114.azurecr.io/devsecops-backend:v1.0.0 # Image trên Azure Container Registry với tag cụ thể
          ports:
            - containerPort: 3000 # Cổng mà code Node.js lắng nghe

          # Bơm biến môi trường từ Kubernetes Secret
          env:
            - name: BLOB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: BLOB_CONNECTION_STRING

---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-backend-service
spec:
  type: LoadBalancer # Yêu cầu Azure cấp một IP Public
  ports:
    - port: 80 # Cổng Public người dùng sẽ gõ trên trình duyệt
      targetPort: 3000 # Map vào cổng 3000 của container bên trong
  selector:
    app: backend
