name: Backend CI/CD Pipeline

# Khi nào Robot được phép chạy?
on:
  push:
    branches: ["main"]
    paths:
      - "backend/**" # Chỉ chạy CI khi có file thay đổi trong thư mục backend, sửa frontend không làm chạy lại backend

#Nhiệm vụ của Robot
jobs:
  build-and-push:
    runs-on: ubuntu-latest # Thuê một máy chủ Ubuntu

    steps:
      #Clone toàn bộ code từ GitHub về cái máy chủ Ubuntu đó
      - name: Lấy mã nguồn (Checkout code)
        uses: actions/checkout@v3

      #Cài đặt công cụ Build Docker
      - name: Thiết lập Docker Buildx
        uses: docker/setup-buildx-action@v2

      #Đăng nhập vào kho chứa Docker Hub bằng chìa khóa bí mật
      - name: Đăng nhập Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #Đóng gói khối bê tông và đẩy lên
      - name: Build và Push Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend # Thư mục chứa mã nguồn
          file: ./backend/Dockerfile # Chỉ định file Dockerfile Production
          push: true # Đóng gói xong thì đẩy lên
          tags: khiemdg/devsecops-backend:latest

          # Quét lỗ hổng bảo mật của Docker Image bằng Trivy
      - name: Quét lỗ hổng Docker Image với Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "khiemdg/devsecops-backend:latest"
          exit-code: "1" # Bắt buộc báo lỗi pipeline nếu có lỗ hổng nghiêm trọng
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH" # Chỉ chặn lại nếu lỗi ở mức Cao và Nghiêm trọng

      # Thiết lập kết nối với cụm AKS bằng Kubeconfig đã lưu trong Secret
      - name: Kết nối với Azure Kubernetes Service (AKS)
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # Chạy lệnh áp dụng file cấu hình vào cụm AKS
      - name: Triển khai lên AKS
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl rollout restart deployment devsecops-backend-deployment
